version: '3.9'
services:
  db:
    image: postgres:15.1
    restart: always
    env_file: ./.env
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_DATABASE
      POSTGRES_USER: $DB_USER
    ports:
      - $POSTGRES_LOCAL_DB_PORT:$POSTGRES_DOCKER_PORT
    volumes:
      - ./db/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
  db-test:
    image: postgres:15.1
    restart: always
    env_file: ./.env
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD_TEST
      POSTGRES_DB: $DB_DATABASE_TEST
      POSTGRES_USER: $DB_USER
    ports:
      - $POSTGRES_LOCAL_DB_PORT_TEST:$POSTGRES_DOCKER_PORT
    volumes:
      - ./db/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
