name: Deploy master branch

on:
  push:
    branches: [master]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint-test:
    name: Format & Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - uses: bahmutov/npm-install@v1
      - run: npm install

      - name: npm format & lint
        run: |
          npm run format
          npm run lint

  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - uses: bahmutov/npm-install@v1
      - run: npm install

      - name: build
        run: npm run build

  deploy-dev:
    name: Deploy to staging
    needs: [lint-test, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - uses: bahmutov/npm-install@v1
      - run: npm install

      - name: Configure AWS profile
        run: npm run ci:configure -- -n git-deploy -p aws -k ${{ secrets.AWS_ACCESS_KEY_ID }} -s ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy
        run: npm run ci:deploy -- -s dev "--aws-profile" git-deploy

  deploy-prod:
    name: Deploy to production
    needs: [deploy-dev]
    environment:
      name: Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - uses: bahmutov/npm-install@v1
      - run: npm install

      - run: npx semantic-release

      - name: Configure AWS profile
        run: npm run ci:configure -- -n git-deploy -p aws -k ${{ secrets.AWS_ACCESS_KEY_ID }} -s ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy
        run: npm run ci:deploy -- -s prod "--aws-profile" git-deploy
